echo off
cls
 
rem This batch file provides a simple way to read about the product:
rem      Zeus Programmers Editor (IDE) for WIN32, v2.15
rem The information you want to read is in the file VENDINFO.DIZ.
rem If you prefer, you can read it using any ordinary text viewer.
rem For example, if the LIST viewer is in your DOS path, you would
rem use the command 'LIST VENDINFO.DIZ'.
 
more < VENDINFO.DIZ
pause
