21
#"        	2 	#include "\c.h"                                                                                                                                                                
#<        	2 	#include <\c.h>                                                                                                                                                                
#d        	2 	#define \c                                                                                                                                                                     
#e        	2 	#endif\n                                                                                                                                                                       
#i        	2 	#ifdef \c\n#endif\n                                                                                                                                                            
#p        	2 	#pragma \c                                                                                                                                                                     
#u        	2 	#undef \c                                                                                                                                                                      
/*        	2 	/* \c */                                                                                                                                                                       
//        	2 	//-- \c                                                                                                                                                                        
dow       	3 	do\n{\n\t\n}\nwhile (\c);\n                                                                                                                                                    
f         	1 	FALSE                                                                                                                                                                          
foi       	3 	for (int i = 0; i < \c; ++i)\n{\n\t\n};\n                                                                                                                                      
foj       	3 	for (int j = 0; j < \c; ++j)\n{\n\t\n};\n                                                                                                                                      
ife       	3 	if (\c == )\n{\n\t\n}\n                                                                                                                                                        
ifg       	3 	if (\c >)\n{\n\t\n}\n                                                                                                                                                          
ifl       	3 	if (\c < )\n{\n\t\n}\n                                                                                                                                                         
mn        	2 	int main(int argc, char *argv[])\n{\n\t\c\n};\n                                                                                                                                
ret       	3 	return \c;                                                                                                                                                                     
swi       	3 	switch (\c)\n{\n\tcase :\n\tbreak;\n\n\bdefault:\n\tbreak;\n\b\b}\n                                                                                                            
t         	1 	TRUE                                                                                                                                                                           
whi       	3 	while (\c)\n{\n}\n                                                                                                                                                             
